### ISSUE TITLE
[Pager] Setting starting page not working?

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1085]
Hi,

I try to use the "page" option for the tablesorterpager addon but it doesn't work. No matter how much content the table has, always page 0 will be shown, e.g.: {..., page: 2, savePages: false, ...}

Is this a known issue?

Best regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

I've never heard of that being an issue. I could help troubleshoot the problem if you would please share some code.

**Comment by a-mair** [comment]
Hi Mottie,

I've simply taken http://mottie.github.io/tablesorter/docs/example-pager.html and changed and modified the "pagerOptions" to read "page: 2, savePages: false".
But you can also try my stripped down demo from here: http://www.andreas-mair.de/temp/ts.tgz

Regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

That appears to be a bug :crying_cat_face: .... if you look at the console, you'll see it's trying to set the page to -1 LOL. I'll sort it out and get that fixed ASAP.

**Comment by a-mair** [comment]
Hi @Mottie,

thanks for the quick fix!
There's another thing that's not working as expected:
If one sets "page" to a higher number than pages exist, then the last page isn't shown but the first page.

Regards,
Andreas

**Comment by Mottie** [comment]
Ok, that should now be fixed in the master branch.

**Comment by a-mair** [comment]
Hi @Mottie,

No, it still doesn't work.

For debugging I modified the example-pager.html to initialize the tablesorter like this:
```javascript
.tablesorter({
    theme: 'blue',
    widthFixed: true,
    widgets: ['zebra', 'filter']   // Added 'filter'
})
```
I modified the "pagerOptions" to read "page: 2, savePages: false" and in jquery.tablesorter.pager.js I changed "getTotalPages" like this:
```
getTotalPages = function( table, p ) {
    console.log("getTotalPages: p.page=" + p.page + " ts.hasWidget( table, 'filter' )=" + ts.hasWidget( table, 'filter' ) + " p.totalPages=" + p.totalPages + " p.filteredPages=" + p.filteredPages);
    return ts.hasWidget( table, 'filter' ) ? Math.min( p.totalPages, p.filteredPages ) : p.totalPages;
},   
```
Now I get the following console log in FireBug:
```
Pager: Initializing
getTotalPages: p.page=2 ts.hasWidget( table, 'filter' )=true p.totalPages=0 p.filteredPages=0
Rebuilt table ( 7ms )
getTotalPages: p.page=2 ts.hasWidget( table, 'filter' )=true p.totalPages=5 p.filteredPages=0
Pager: Changing to page -1
```

There has been no filtering done yet, well actually there's no filter text set yet. In that state there's no "<input>" where one can enter filter text.

Regards,
Andreas

**Comment by Mottie** [comment]
Ok, *that* should finally fix the problem \*crosses fingers\*.

**Comment by a-mair** [comment]
@Mottie 
Yes, that's fixed now, but there's another thing:
I need to initially display the last page. AFAIK there's no special value for the "page" setting (like for example "-1") to get this. I try to avoid an extra "<tr>" counting so I use "99999".

This doesn't work if I set this in "pagerOptions", but it works if I trigger "pageSet".
I'd expect equal results.
What about defining a special value for the last page? Maybe "-1"? If someone will ever need this could also be extended to let negative numbers start counting from the last page...

Regards,
Andreas
