### ISSUE TITLE
scroller widths

### ISSUE THREAD

**Issue by davidh71** [Mottie/tablesorter#1468]
Hi,
Having an issue with the column widths not matching the body widths.
**example**: http://jsfiddle.net/u7whxf1e/1/

**problems**:
1, on first render the columns don't align
2. on window resize they DO align, but they are forced fixed width which i would prefer not to have.

Bug? or am i missing something.
Many thanks!!

**Comment by Mottie** [comment]
Hi @davidh71!

Thanks for reporting this issue. I just fixed the column alignment issue in the master branch ([demo](http://jsfiddle.net/Mottie/u7whxf1e/2/)). A new release is planned once I get #1467 fixed.

As for forcing a width on the columns, that's actually the input that is doing that. All inputs have a set width in the browser. The filter widget sets their width to `95%` of the column width, but it still causes the table to adjust. If you want to narrow the columns, add a class name to each header (`th`) to set the width of the column using a percentage.

**Comment by davidh71** [comment]
Hi, Thanks for responding so fast.  
With the demo link you provided - if i take out the filter widget, i'm still getting some misalignment on inital load.  Then when i resize it aligns.  Do you see that as well ?  
i updated my fiddle with the same : http://jsfiddle.net/u7whxf1e/3/

**Comment by Mottie** [comment]
Hmm, it looks fine in Chrome, but I do see the one pixel misalignment in Firefox... I'll see what I can do.

**Comment by davidh71** [comment]
It looks like the alignment depends on the size of the columns.  When it's this size see the alignment - chrome ubuntu.. do you see the same thing?
![screenshot from 2017-10-21 05-06-51](https://user-images.githubusercontent.com/2146176/31850311-d07f712c-b61d-11e7-920b-9e804f6ec038.png)

**Comment by Mottie** [comment]
I just released a new version, but sadly I forgot about this alignment issue. I'll include a fix (hopefully) in the next release.

**Comment by Mottie** [comment]
This looks like it was fixed in https://github.com/Mottie/tablesorter/commit/8beec62953607f422b07ca13ae4344a38e9e0d8f. Would you please verify.
