### ISSUE TITLE
Get Number of Row in TBODY in TableSorter using Scroller Plugin

### ISSUE THREAD

**Issue by hatimhaidry** [Mottie/tablesorter#1472]
Hi Mottie,

Thanks for developing and sharing a very useful plugin which has lot of features..

I am using table sorter plugin version 2.29

When I use scroller plugin along with 'zebra', 'resizable', 'stickyHeaders', 'filter' plugins, and retrieve the number of rows in tbody of the table using 
var NoOfRowsInItmLst = document.getElementById("tblItmLstBody").rows.length;,

It returns n + 1 rows where n is the actual data row that my page filled it and 1 row is the hidden row that has been added by the 'scroller' plugin. If I remove scroller plugin that it returns correct row.

Is there any method in tablesorter plugin which should returns the correct row in table's tbody?

Thanks & Regards
Hatim

**Comment by Mottie** [comment]
Hi @hatimhaidry!

Get the [`config` variable](https://mottie.github.io/tablesorter/docs/#config) for the table, then check the [`config.totalRows` value](https://mottie.github.io/tablesorter/docs/#variable-totalrows). I set up [this demo](https://jsfiddle.net/Mottie/ft3qyjns/12/) for you.

```js
$(function() {
	function showRows(table) {
  	alert('The tbody has ' + table.config.totalRows + ' rows');
  }
  $('table').tablesorter({
    widgets: ['scroller'],
    initialized: showRows
  });
});
```

**Comment by hatimhaidry** [comment]
Hi Mottie,

Thanks for replying and given me the solution along with demo.

When I use the same demo to add "resizable" widget along with 'zebra', 'scroller' widgets, the column resizing does not happen. 

Please help in this regard

Thanks & Regards
Hatim

**Comment by Mottie** [comment]
The resizable widget isn't currently compatible with the scroller widget. Sadly, the scroller widget has a lot of incompatibilities with other widgets.

**Comment by hatimhaidry** [comment]
Hi Mottie,

I hope you soon overcome these incompatibilities.

Is there any other plugin we would use for scroller functionality with tablesorter?

Hatim

**Comment by Mottie** [comment]
If you must have a scroller-like view, then I might have to suggest you check out [datatables](https://github.com/DataTables/DataTables/).

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by hatimhaidry** [comment]
As you have said that the Scroller widget has lot of incompatibilities with other widgets and suggested to check for datatables. Hence I am looking for datatables.

However, the issue is still there in using tablesorter plugin. And I would appreciate and need to use tablesorter in our application if this issue resolve. 

Hence requesting you to please resolve scroller widget incompatibilities with other widgets

Thanks
Hatim

**Comment by Mottie** [comment]
The scroller is currently incompatible with the resizable widget. I've centralized all of the scroller widget incompatibilities into one issue (#1487). Please follow any progress there.
