### ISSUE TITLE
Tablesorter sometimes not being loaded into jQuery with require()

### ISSUE THREAD

**Issue by soundasleep** [Mottie/tablesorter#1551]
On 2.30.3, we've occasionally had a very odd issue, where Tablesorter is loaded, but not added to jQuery.fn, so that we end up with "tablesorter is not a function" errors.

```coffee
$ = require('jquery')
tablesorter = require('tablesorter')

settings = {
  theme: 'materialize'
}

$(document).on 'load', () ->
  window.tablesorter = tablesorter

  $("table.sortable").each (index, element) ->
      $(element).tablesorter(settings) # sometimes fails with a "$(...).tablesorter is not a function"
```

It seems like it's a weird dependency/build order thing, because sometimes it works, sometimes it doesn't, but in every case, `window.tablesorter` is set. We haven't found a way to solve this issue permanently, except by changing the way we initialise tablesorter, to basically duplicate the existing $.fn = in tablesorter (yuck!):

```coffee
  $("table.sortable").each (index, element) ->
    # merge & extend config options
    c = $.extend( true, {}, tablesorter.defaults, settings, tablesorter.instanceMethods )
    # save initial settings
    c.originalSettings = settings
    # create a table from data (build table widget)
    tablesorter.setup element, c
```

I'm wondering if it's possible/sensible to add a method to Tablesorter that allows it to be setup on an arbitrary element, without needing to go though $/jQuery? What do you think?

For example:

```coffee
$ = require('jquery')
tablesorter = require('tablesorter')

$(document).on 'load', () ->
  $("table.sortable").each (index, element) ->
    tablesorter.apply(element)  # or tablesorter.apply($, element)
```

**Comment by Mottie** [comment]
Hi @soundasleep!

Hmm, it sounds like the `require('tablesorter')` isn't finding jQuery... I searched [Stack Overflow](https://stackoverflow.com/a/25978543/145346) and there's a recommendation to do the following:

```js
window.jQuery = require('jquery');
window.$ = window.jQuery;
require('tablesorter'); // it will attach itself to jQuery

$(function() {
  $('.table.sortable').tablesorter();
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by soundasleep** [comment]
I've just tried this again and unfortunately it's still 100% an issue. Here's what we tried:

```
window.jQuery = $ = require('jquery')
tablesorter = require('tablesorter')

settings = {
  theme: 'materialize'
}

$(document).on 'load', () ->
  window.tablesorter = tablesorter
  $("table.sortable").each (index, element) ->
    $(element).tablesorter settings
```

This still throws `i(...).tablesorter is not a function` and tablesorter doesn't work, but `window.tablesorter` is still set.

We're not able to pollute `window.$`, we already have `window.jQuery`.

What about our earlier suggestion, of having tablesorter export in such a way that we can pass in a jQuery instance for it to attach itself to?

```
$ = require('jquery')
tablesorter = require('tablesorter')    # or require('tablesorter')($) if you need jQuery to load

$(document).on 'load', () ->
  $("table.sortable").each (index, element) ->
    tablesorter.apply(element)      # or tablesorter.apply($, element) if you need jQuery to init
```

**Comment by Mottie** [comment]
I'm not sure what to tell you... it sounds like there is more than one version of jQuery being loaded. How is the javascript being loaded? What does the HTML look like?

**Comment by soundasleep** [comment]
I was wondering if I maybe had two versions of jQuery being loaded, but no, I can't find anything that might suggest that. You can look at the production site: https://cryptfolio.com (it has sourcemaps) 

It's really confusing! I'm not sure what it could be either. For now, using the monkey-patching-esque workaround mentioned above is working reliably.

**Comment by Federico-G** [comment]
I see that your page use a lot of scripts with async, Are you sure that jQuery and tablesorter are loaded property by the time you are using them?
For example, when you are doing:
```javascript
window.jQuery = $ = require('jquery')
```
tablesorter isn't loaded yet

**Comment by soundasleep** [comment]
Thank you for following this up. I've just tried this, and had the same behaviour:

```coffee
window.jQuery = $ = require('jquery')
window.tablesorter = tablesorter = require('tablesorter')

debug = false

settings = {
  theme: 'materialize'
}

$(document).on 'load', () ->
  window.tablesorter2 = tablesorter

  $("table.sortable").each (index, element) ->
    $(element).tablesorter settings
```

Both `window.tablesorter` and `window.tablesorter2` are set, and `window.tablesorter === window.tablesorter2` is `true`. But it's not being attached to `$`.  `window.jQuery.tablesorter` is also undefined.

**Comment by soundasleep** [comment]
Just tried that - no difference.
